language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - IMAGE_REPO=vyahello/pep8-checker IMAGE_VERSION=0.0.2
addons:
  apt:
    update: true
install:
  - pip install pip==20.2.0
  - pip install -r requirements.txt -U
  - pip install -r requirements-dev.txt -U
script:
    - ./analyse-source-code.sh
    - bash test-docker.sh
after_success:
  - coveralls
notifications:
  email: false
